export const CATEGORIES = [
    "",
    "Breaks de taille intermédiaire",
    "Breaks de taille intermédiaire à grande",
    "Camions pick-up standard",
    "Camions pick-up standard deux roues motrices",
    "Camions pick-up standard/deux roues motrices",
    "Camions pick-up standard quatre roues motrices",
    "Deux places",
    "Grandes voitures",
    "Monospace - deux roues motrices",
    "Monospace - quatre roues motrices",
    "Petits breaks",
    "Petits camions pick-up",
    "Petits camions pick-up deux roues motrices",
    "Petits camions pick-up quatre roues motrices",
    "Petit véhicule utilitaire sportif deux roues motrices",
    "Petit véhicule utilitaire sportif quatre roues motrices",
    "Vans",
    "Vans passagers",
    "Vans, type passager",
    "Vans, type utilitaire",
    "Véhicule à usage spécial",
    "Véhicule à usage spécial deux roues motrices",
    "Véhicule à usage spécial quatre roues motrices",
    "Véhicules à usage spécial",
    "Véhicules à usage spécial/deux roues motrices",
    "Véhicules à usage spécial/quatre roues motrices",
    "Véhicule utilitaire sportif - deux roues motrices",
    "Véhicule utilitaire sportif - quatre roues motrices",
    "Véhicule utilitaire sportif standard deux roues motrices",
    "Véhicule utilitaire sportif standard quatre roues motrices",
    "Voitures compactes",
    "Voitures de taille intermédiaire",
    "Voitures mini-compactes",
    "Voitures sous-compactes"
];

export const TRANSMISSIONS = [
    "",
    "Manuelle 3 vitesses",
    "Automatique 9 vitesses",
    "Automatique 7 vitesses",
    "Automatique (AM-S9)",
    "Automatique 8 vitesses",
    "Automatique (AM-8)",
    "Automatique (AV-S10)",
    "Automatique (AV-S7)",
    "Automatique 5 vitesses",
    "Automatique (AM6)",
    "Automatique (AM-S6)",
    "Automatique (S9)",
    "Automatique (AM-S7)",
    "Manuelle 7 vitesses",
    "Automatique (A1)",
    "Automatique (AV-S1)",
    "Automatique (L4)",
    "Automatique (S10)",
    "Automatique (L3)",
    "Automatique (AM5)",
    "Automatique (rapports de vitesse variables)",
    "Manuelle 4 vitesses",
    "Automatique 4 vitesses",
    "Automatique (AM7)",
    "Automatique (AV-S6)",
    "Automatique 6 vitesses",
    "Automatique (AV-S8)",
    "Automatique (AM-S10)",
    "Automatique (AM-S8)",
    "Manuelle 6 vitesses",
    "Automatique (S4)",
    "Automatique (S8)",
    "Automatique (S7)",
    "Automatique (S5)",
    "Automatique (S6)",
    "Automatique 10 vitesses",
    "Manuelle 5 vitesses",
    "Automatique 3 vitesses"
];

export const FUELS = [
    "",
    "Diesel",
    "Essence",
    "Essence intermédiaire",
    "Essence premium",
    "Gaz naturel"
];

export const YEARS = [
    "",
    ...Array.from(
        { length: 2024 - 1984 + 1 }, 
        (_, i) => (1984 + i).toString()
    )
];

export const MAKES = [
    "",
    "Acura", "Alfa Romeo", "American Motors Corporation", "AM General",
    "ASC Incorporated", "Aston Martin", "Audi", "Aurora Cars Ltd",
    "Autokraft Limited", "Bentley", "Bertone", "Bill Dovell Motor Car Company",
    "Bitter Gmbh and Co. Kg", "BMW", "BMW Alpina", "Bugatti", "Buick",
    "Cadillac", "CCC Engineering", "Chevrolet", "Chrysler",
    "Consulier Industries Inc", "CX Automotive", "Dabryan Coach Builders Inc",
    "Dacia", "Daewoo", "Daihatsu", "Dodge", "Eagle",
    "Environmental Rsch and Devp Corp", "E. P. Dutton, Inc.", "Evans Automobiles",
    "Excalibur Autos", "Federal Coach", "Ferrari", "Fiat", "Fisker", "Ford",
    "General Motors", "Genesis", "Geo", "GMC", "Goldacre",
    "Grumman Allied Industries", "Grumman Olson", "Honda", "Hummer", "Hyundai",
    "Import Foreign Auto Sales Inc", "Import Trade Services", "INEOS Automotive",
    "Infiniti", "Isis Imports Ltd", "Isuzu", "Jaguar", "JBA Motorcars, Inc.",
    "Jeep", "J.K. Motors", "Karma", "Kia", "Koenigsegg", "Laforza Automobile Inc",
    "Lambda Control Systems", "Lamborghini", "Land Rover", "Lexus", "Lincoln",
    "London Coach Co Inc", "London Taxi", "Lotus", "Mahindra", "Maserati",
    "Maybach", "Mazda", "Mcevoy Motors", "McLaren Automotive", "Mercedes-Benz",
    "Mercury", "Merkur", "MINI", "Mitsubishi", "Mobility Ventures LLC", "Morgan",
    "Nissan", "Oldsmobile", "Pagani", "Panos", "Panoz Auto-Development",
    "Panther Car Company Limited", "PAS, Inc", "PAS Inc - GMC", "Peugeot",
    "Pininfarina", "Plymouth", "Polestar", "Pontiac", "Porsche",
    "Quantum Technologies", "Qvale", "Ram", "Red Shift Ltd.", "Renault",
    "Rolls-Royce", "Roush Performance", "RUF Automobile", "Ruf Automobile Gmbh",
    "Saab", "Saleen", "Saleen Performance", "S and S Coach Company  E.p. Dutton",
    "Saturn", "Scion", "Shelby", "smart", "Spyker", "SRT", "Sterling", "STI",
    "Subaru", "Superior Coaches Div E.p. Dutton", "Suzuki", "Tecstar, LP",
    "Texas Coach Company", "Toyota", "TVR Engineering Ltd", "Vector",
    "Vixen Motor Company", "Volga Associated Automobile", "Volkswagen", "Volvo",
    "VPG", "Wallace Environmental", "Yugo"
]; 